#!/bin/sh

echo "<P>last updated `date`\n"
echo "<P><BLOCKQUOTE>"
grep "^\*" foo | cut -f2 -d' ' | egrep -v "hub" | \
	egrep -v "spanish-inquisition" | \
	 sort -t'.' +2 | \
	while read line
	do
		echo "<a href=irc://$line:6666>$line</a><br>"
	done
